### ISSUE TITLE
bash visualizer error

### ISSUE THREAD

**Issue by mayidu** [Kei18/mapf-IR#15]
hi, I had some error when I use commend 'bash ./visualizer/scripts/build_macos.sh '

can you help me to solve this problem, thanks!

and  have  python code for this, thanks!

such as :
Uncompressing libraries osx from openFrameworksLibs_master_osx2.tar.bz2
Uncompressing libraries osx from openFrameworksLibs_master_osx3.tar.bz2
Uncompressing libraries osx from openFrameworksLibs_master_osx4.tar.bz2
Copying opencv to ofxOpenCv
Copying libusb to ofxKinect
Copying assimp to ofxAssimpModelLoader
Copying libxml2 to ofxSvg
Copying svgtiny to ofxSvg
Copying poco to ofxPoco
Copying openssl to ofxPoco
Package gstreamer-app-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-app-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-app-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package gstreamer-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package gstreamer-video-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-video-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-video-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package gstreamer-base-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-base-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-base-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
Package 'alsa', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package gstreamer-app-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-app-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-app-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package gstreamer-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package gstreamer-video-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-video-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-video-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package gstreamer-base-0.10 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-base-0.10.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gstreamer-base-0.10', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
Package 'alsa', required by 'virtual:world', not found
/bin/sh: line 0: return: can only `return' from a function or sourced script
/home/project/MAPF/mapf-IR/visualizer/../third_party/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.shared.mk:305: *** couldn't find gstreamer-app-0.10 gstreamer-0.10 gstreamer-video-0.10 gstreamer-base-0.10 alsa 0 pkg-config package or it's dependencies, did you run the latest install_dependencies.sh?.  Stop.

**Comment by Kei18** [comment]
Hi, 

Could you provide your macOS version?

If you are with macOS 11.x or later, please try the following.

```sh
git submodule update --remote
bash ./third_party/openFrameworks/scripts/osx/download_libs.sh
cd visualizer
make build
cd ..
chmod +x ./visualize.sh
```

Note: I do not have Python code for this repository.

**Comment by mayidu** [comment]
thanks for your reply.
my device is redhat, not macOS, should I use which download_libs.sh?

thanks!

**Comment by Kei18** [comment]
I see. Unfortunately, the visualizer is developed for macOS. I do not know whether it works in Red Hat Linux.

The problem is the installation of openFrameworks.  I think it's possible, but not sure. Please refer to the following URL.
https://openframeworks.cc/setup/linux-install/

(Sorry but right now, I do not have an environment to test it.)

**Comment by mayidu** [comment]
thanks! I will try.
