### ISSUE TITLE
Visualiser for Ubuntu

### ISSUE THREAD

**Issue by tejas2112** [Kei18/mapf-IR#16]
How do I get the visualiser running for ubuntu? Could you please help me with this?

**Comment by Kei18** [comment]
Hi,

The problem is the installation of openFrameworks. I think it's possible, but I'm not sure. Please refer to the following:
https://openframeworks.cc/setup/linux-install/

c.f., recently, I forked the visualizer from this repo:
https://github.com/Kei18/mapf-visualizer

Cheers,
Keisuke

**Comment by Kei18** [comment]
Check https://github.com/kei18/mapf-visualizer
