### ISSUE TITLE
Errors encountered when running `build_macos.sh` on OS X 11.4

### ISSUE THREAD

**Issue by troysung** [Kei18/mapf-IR#7]
Hi, there. I was trying to build the visualizer on my mac. It seems that the 5th line of build_macos.sh `bash ./scripts/osx/download_libs.sh -v 0.11.0` should be `bash ./scripts/dev/download_libs.sh -v 0.11.0` since there is no folder named osx. I fixed it and it worked fine but failed when running `make build` in visualizer folder. I got the following error:

```
make: *** No rule to make target `/Users/vodkasoul/mapf-IR/visualizer/../third_party/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.  Stop.
``` 

I couldn't find a `openFrameworksCompiled` folder and I am wondering if there was something went wrong in previous steps.

**Comment by Kei18** [comment]
Hi, thank you for reporting a bug.

I tried both 10.15 and 11.2 then found the build error only on 11.2. So this error seems specific to Big Sur.

As a temporary measure, please try the following script. In my environment of 11.2, it works fine.
```sh
git clone --recursive https://github.com/Kei18/mapf-IR.git
cd mapf-IR
git submodule update --remote
bash ./third_party/openFrameworks/scripts/osx/download_libs.sh
cd visualizer
make build
cd ..
chmod +x ./visualize.sh
```
(then run `visualize.sh` with the planning result)

I am currently busy and difficult to find time to fix the repo properly. I hope the above will help you.

Cheers,
Kei

**Comment by troysung** [comment]
Sorry, I did not notice that `git clone` command needs `--recursive` argument to include submodules. I am terribly sorry to bother you. It works fine for me now. Thanks for your reply.

Regards.

**Comment by Kei18** [comment]
That's okay. If you have any problems, don't hesitate to ask me.
